name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Get yadm and install the files
      run: |
        brew install git yadm
        yadm clone --bootstrap https://github.com/$GITHUB_REPOSITORY
        nvim -es +checkhealth
