name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]

    steps:
    - name: Get yadm and install the files
      run: |
        sudo apt-get install git yadm || brew install git yadm
        yadm clone --bootstrap https://github.com/$GITHUB_REPOSITORY
        nvim -es +checkhealth
